package com.cardio_generator.outputs;

/**
 * The OutputStrategy interface defines a contract for classes that handle output
 * of health data generated by patient data generators.
 */
public interface OutputStrategy {
    /**
     *Outputs health data for a patient with the specified timestamp, label, and data.
     *
     * @param patientId is the patient's ID.
     * @param timestamp is the time stamp at which the health data was generated.
     * @param label is the label describing the type of data from HealthDataSimulator.
     * @param data is the actual health data.
     */
    void output(int patientId, long timestamp, String label, String data);
}
